/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { AlternativeContract } from "./alternativeContract";

export interface Alternative {
  contractId: string;
  contract: AlternativeContract;
}
