/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type ApplicationType =
  (typeof ApplicationType)[keyof typeof ApplicationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationType = {
  Application: "Application",
} as const;
