/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { ApplicationAllOf } from "./applicationAllOf";
import type { ApplicationType } from "./applicationType";

export type Application = Contract &
  ApplicationAllOf & {
    type: ApplicationType;
  };
