/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type CloudflareTunnelAllOf = {
  /** @nullable */
  accountId?: string | null;
  /** @nullable */
  tunnelName?: string | null;
  /** @nullable */
  tunnelId?: string | null;
  /** @nullable */
  token?: string | null;
  installed?: boolean;
  cloudflareApiConnection: string;
  container: string;
};
