/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type CloudflareTunnelType =
  (typeof CloudflareTunnelType)[keyof typeof CloudflareTunnelType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CloudflareTunnelType = {
  CloudflareTunnel: "CloudflareTunnel",
} as const;
