/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type CloudflareApiConnectionAllOf = {
  /** @nullable */
  token?: string | null;
  installed?: boolean;
};
