/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { CloudflareApiConnectionAllOf } from "./cloudflareApiConnectionAllOf";
import type { CloudflareApiConnectionType } from "./cloudflareApiConnectionType";

export type CloudflareApiConnection = Contract &
  CloudflareApiConnectionAllOf & {
    type: CloudflareApiConnectionType;
  };
