/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { CloudflareTunnelAllOf } from "./cloudflareTunnelAllOf";
import type { CloudflareTunnelType } from "./cloudflareTunnelType";

export type CloudflareTunnel = Contract &
  CloudflareTunnelAllOf & {
    type: CloudflareTunnelType;
  };
