/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type CloudflareApiConnectionType =
  (typeof CloudflareApiConnectionType)[keyof typeof CloudflareApiConnectionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CloudflareApiConnectionType = {
  CloudflareApiConnection: "CloudflareApiConnection",
} as const;
