/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type ConnectExternalContainerType =
  (typeof ConnectExternalContainerType)[keyof typeof ConnectExternalContainerType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConnectExternalContainerType = {
  ConnectExternalContainer: "ConnectExternalContainer",
} as const;
