/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Protocol } from "./protocol";

export interface ContainerPort {
  internalPort: number;
  externalPort: number;
  protocol: Protocol;
}
