/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type ContainerType = (typeof ContainerType)[keyof typeof ContainerType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContainerType = {
  Container: "Container",
} as const;
