/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { ContainerContractAllOf } from "./containerContractAllOf";
import type { ContainerContractType } from "./containerContractType";

export type ContainerContract = Contract &
  ContainerContractAllOf & {
    Type: ContainerContractType;
  };
