/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export interface Contract {
  Type: string;
  name: string;
  /** @nullable */
  installer?: string | null;
}
