/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { ContainerAllOfEnv } from "./containerAllOfEnv";
import type { ContainerAllOfLabels } from "./containerAllOfLabels";
import type { ContainerAllOfMounts } from "./containerAllOfMounts";
import type { ContainerPort } from "./containerPort";

export type ContainerAllOf = {
  /** @nullable */
  containerName?: string | null;
  /** @nullable */
  networkName?: string | null;
  mountDockerSocket: boolean;
  readonly installed?: boolean;
  /** @nullable */
  command: string[] | null;
  env: ContainerAllOfEnv;
  labels: ContainerAllOfLabels;
  mounts: ContainerAllOfMounts;
  ports: ContainerPort[];
  network: string;
  networkAliases: string[];
  /** @nullable */
  imageName: string | null;
};
