/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type ContainerContractType =
  (typeof ContainerContractType)[keyof typeof ContainerContractType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContainerContractType = {
  Container: "Container",
} as const;
