/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { ContainerMount } from "./containerMount";

export type ContainerAllOfMounts = { [key: string]: ContainerMount };
