/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type DaemonAllOf = {
  /** @nullable */
  daemonName?: string | null;
  readonly installed?: boolean;
  /** @nullable */
  command: string[] | null;
  /** @nullable */
  preCommands: string[][] | null;
};
