/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type DaemonType = (typeof DaemonType)[keyof typeof DaemonType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DaemonType = {
  Daemon: "Daemon",
} as const;
