/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { DaemonAllOf } from "./daemonAllOf";
import type { DaemonType } from "./daemonType";

export type Daemon = Contract &
  DaemonAllOf & {
    type: DaemonType;
  };
