/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type DependencyType =
  (typeof DependencyType)[keyof typeof DependencyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DependencyType = {
  Dependency: "Dependency",
} as const;
