/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { DependencyAllOf } from "./dependencyAllOf";
import type { DependencyType } from "./dependencyType";

export type Dependency = Contract &
  DependencyAllOf & {
    Type: DependencyType;
  } & Required<
    Pick<
      Contract &
        DependencyAllOf & {
          Type: DependencyType;
        },
      "Type" | "following" | "preceding" | "following" | "preceding"
    >
  >;
