/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Protocol } from "./protocol";

export type DockerPortEndpointAllOf = {
  name: string;
  ip: string;
  port: number;
  protocol: Protocol;
  readonly url: string;
};
