/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Resource } from "./resource";
import type { DockerPortEndpointAllOf } from "./dockerPortEndpointAllOf";
import type { DockerPortEndpointType } from "./dockerPortEndpointType";

export type DockerPortEndpoint = Resource &
  DockerPortEndpointAllOf & {
    Type: DockerPortEndpointType;
  };
