/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type DockerContainerType =
  (typeof DockerContainerType)[keyof typeof DockerContainerType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DockerContainerType = {
  DockerContainer: "DockerContainer",
} as const;
