/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type DockerNetworkType =
  (typeof DockerNetworkType)[keyof typeof DockerNetworkType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DockerNetworkType = {
  DockerNetwork: "DockerNetwork",
} as const;
