/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Resource } from "./resource";
import type { DockerAttachedNetworkAllOf } from "./dockerAttachedNetworkAllOf";
import type { DockerAttachedNetworkType } from "./dockerAttachedNetworkType";

export type DockerAttachedNetwork = Resource &
  DockerAttachedNetworkAllOf & {
    Type: DockerAttachedNetworkType;
  };
