/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type DockerPortEndpointType =
  (typeof DockerPortEndpointType)[keyof typeof DockerPortEndpointType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DockerPortEndpointType = {
  DockerPortEndpoint: "DockerPortEndpoint",
} as const;
