/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type DockerVolumeType =
  (typeof DockerVolumeType)[keyof typeof DockerVolumeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DockerVolumeType = {
  DockerVolume: "DockerVolume",
} as const;
