/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type DockerApiConnectionType =
  (typeof DockerApiConnectionType)[keyof typeof DockerApiConnectionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DockerApiConnectionType = {
  DockerApiConnection: "DockerApiConnection",
} as const;
