/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Resource } from "./resource";
import type { DockerNetworkAllOf } from "./dockerNetworkAllOf";
import type { DockerNetworkType } from "./dockerNetworkType";

export type DockerNetwork = Resource &
  DockerNetworkAllOf & {
    Type: DockerNetworkType;
  };
