/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Resource } from "./resource";
import type { DockerVolumeAllOf } from "./dockerVolumeAllOf";
import type { DockerVolumeType } from "./dockerVolumeType";

export type DockerVolume = Resource &
  DockerVolumeAllOf & {
    Type: DockerVolumeType;
  };
