/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type DockerAttachedNetworkType =
  (typeof DockerAttachedNetworkType)[keyof typeof DockerAttachedNetworkType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DockerAttachedNetworkType = {
  DockerAttachedNetwork: "DockerAttachedNetwork",
} as const;
