/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type DomainType = (typeof DomainType)[keyof typeof DomainType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DomainType = {
  Domain: "Domain",
} as const;
