/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { ExecutionPlanResponseParameters } from "./executionPlanResponseParameters";

export interface ExecutionPlanResponse {
  children: ExecutionPlanResponse[];
  parameters: ExecutionPlanResponseParameters;
  typeName: string;
}
