/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { ExecutionPlanContracts } from "./executionPlanContracts";
import type { ExecutionPlanAlternativesItem } from "./executionPlanAlternativesItem";

export interface ExecutionPlan {
  contracts: ExecutionPlanContracts;
  alternatives: ExecutionPlanAlternativesItem[];
}
