/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { ExecutionPlanRequestParameters } from "./executionPlanRequestParameters";

export interface ExecutionPlanRequest {
  children: ExecutionPlanRequest[];
  parameters: ExecutionPlanRequestParameters;
  selectedIndex: number;
}
