/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { ExecutionPlan } from "./executionPlan";

export interface ExecutionPlanSelector {
  readonly children: readonly ExecutionPlan[];
  selectedIndex: number;
}
