/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { ExecutionPlanSelector } from "./executionPlanSelector";
import type { ExecutionPlanParameters } from "./executionPlanParameters";

export interface ExecutionPlan {
  readonly children: readonly ExecutionPlanSelector[];
  readonly parameters: ExecutionPlanParameters;
  readonly typeName: string;
}
