/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { CloudflareApiConnection } from "./cloudflareApiConnection";
import type { CloudflareTunnel } from "./cloudflareTunnel";
import type { Container } from "./container";
import type { Dependency } from "./dependency";
import type { DockerApiConnection } from "./dockerApiConnection";
import type { Domain } from "./domain";
import type { File } from "./file";
import type { HttpEndpoint } from "./httpEndpoint";
import type { Mysql } from "./mysql";
import type { Network } from "./network";
import type { Optional } from "./optional";
import type { Package } from "./package";
import type { Parameter } from "./parameter";
import type { Password } from "./password";
import type { PortEndpoint } from "./portEndpoint";
import type { Postgresql } from "./postgresql";
import type { Redis } from "./redis";
import type { Selector } from "./selector";
import type { Substitute } from "./substitute";
import type { Volume } from "./volume";

export type ExecutionPlanContractsItem =
  | CloudflareApiConnection
  | CloudflareTunnel
  | Container
  | Dependency
  | DockerApiConnection
  | Domain
  | File
  | HttpEndpoint
  | Mysql
  | Network
  | Optional
  | Package
  | Parameter
  | Password
  | PortEndpoint
  | Postgresql
  | Redis
  | Selector
  | Substitute
  | Volume;
