/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { FileContractAllOf } from "./fileContractAllOf";
import type { FileContractType } from "./fileContractType";

export type FileContract = Contract &
  FileContractAllOf & {
    Type: FileContractType;
  };
