/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { FileAllOf } from "./fileAllOf";
import type { FileType } from "./fileType";

export type File = Contract &
  FileAllOf & {
    Type: FileType;
  } & Required<
    Pick<
      Contract &
        FileAllOf & {
          Type: FileType;
        },
      "Type" | "text" | "volumeName" | "text" | "volumeName"
    >
  >;
