/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type FileAllOf = {
  path: string;
  /** @nullable */
  text?: string | null;
  /** @nullable */
  owner?: number | null;
  /** @nullable */
  group?: number | null;
  volume: string;
};
