/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type FileContractType =
  (typeof FileContractType)[keyof typeof FileContractType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileContractType = {
  File: "File",
} as const;
