/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type GenericHttpEndpointType =
  (typeof GenericHttpEndpointType)[keyof typeof GenericHttpEndpointType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GenericHttpEndpointType = {
  GenericHttpEndpoint: "GenericHttpEndpoint",
} as const;
