/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type GenericHttpEndpointAllOf = {
  type: string;
  url: string;
  readonly host: string;
  readonly port: number;
  readonly ssl: boolean;
};
