/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Resource } from "./resource";
import type { GeneratedPasswordAllOf } from "./generatedPasswordAllOf";
import type { GeneratedPasswordType } from "./generatedPasswordType";

export type GeneratedPassword = Resource &
  GeneratedPasswordAllOf & {
    Type: GeneratedPasswordType;
  };
