/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type GeneratedPasswordType =
  (typeof GeneratedPasswordType)[keyof typeof GeneratedPasswordType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GeneratedPasswordType = {
  GeneratedPassword: "GeneratedPassword",
} as const;
