/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Container } from "./container";
import type { File } from "./file";
import type { HttpEndpoint } from "./httpEndpoint";
import type { Mount } from "./mount";
import type { Network } from "./network";
import type { Package } from "./package";
import type { Parameter } from "./parameter";
import type { PortEndpoint } from "./portEndpoint";
import type { Substitute } from "./substitute";
import type { Volume } from "./volume";

export type GetPackagesIdPlan200Item =
  | Container
  | File
  | HttpEndpoint
  | Mount
  | Network
  | Package
  | Parameter
  | PortEndpoint
  | Substitute
  | Volume;
