/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { HandlerExceptionResultContract } from "./handlerExceptionResultContract";

export interface HandlerExceptionResult {
  message: string;
  solution: string;
  contract: HandlerExceptionResultContract;
}
