/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Resource } from "./resource";
import type { HttpEndpointAllOf } from "./httpEndpointAllOf";
import type { HttpEndpointType } from "./httpEndpointType";

export type HttpEndpoint = Resource &
  HttpEndpointAllOf & {
    Type: HttpEndpointType;
  };
