/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type HttpEndpointAllOf = {
  port: number;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  networkName?: string | null;
  installed?: boolean;
  container: string;
  domain: string;
};
