/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { HttpEndpointAllOf } from "./httpEndpointAllOf";
import type { HttpEndpointType } from "./httpEndpointType";

export type HttpEndpoint = Contract &
  HttpEndpointAllOf & {
    Type: HttpEndpointType;
  };
