/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { GenericHttpEndpoint } from "./genericHttpEndpoint";
import type { TraefikHttpEndpoint } from "./traefikHttpEndpoint";

/**
 * @nullable
 */
export type HttpEndpointAllOfResult =
  | GenericHttpEndpoint
  | TraefikHttpEndpoint
  | null;
