/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { HttpEndpointAllOfResult } from "./httpEndpointAllOfResult";

export type HttpEndpointAllOf = {
  port: number;
  /** @nullable */
  result?: HttpEndpointAllOfResult;
  container: string;
  domain: string;
};
