/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type HttpEndpointType =
  (typeof HttpEndpointType)[keyof typeof HttpEndpointType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HttpEndpointType = {
  HttpEndpoint: "HttpEndpoint",
} as const;
