/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type HttpEndpointContractType =
  (typeof HttpEndpointContractType)[keyof typeof HttpEndpointContractType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HttpEndpointContractType = {
  HttpEndpoint: "HttpEndpoint",
} as const;
