/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type HttpEndpointAllOf = {
  port: number;
  /** @nullable */
  traefikRouterName?: string | null;
  /** @nullable */
  networkName?: string | null;
  /** @nullable */
  cloudflareZoneId?: string | null;
  container: string;
  /** @nullable */
  resultSsl: boolean | null;
  /** @nullable */
  resultHost: string | null;
  /** @nullable */
  resultPort: number | null;
};
