/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export interface IHandlerLazy {
  TypeName: string;
  /** @nullable */
  ApplicationName?: string | null;
}
