/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export * from "./application";
export * from "./installRequest";
export * from "./package";
export * from "./parametersResponse";
export * from "./state";
export * from "./volume";
