/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { StringStringKeyValuePair } from "./stringStringKeyValuePair";

export interface InstallRequest {
  name: string;
  parameters: StringStringKeyValuePair[][];
}
