/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type LocalPathType = (typeof LocalPathType)[keyof typeof LocalPathType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocalPathType = {
  LocalPath: "LocalPath",
} as const;
