/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { MountContractAllOf } from "./mountContractAllOf";
import type { MountContractType } from "./mountContractType";

export type MountContract = Contract &
  MountContractAllOf & {
    Type: MountContractType;
  };
