/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type MountContractType =
  (typeof MountContractType)[keyof typeof MountContractType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MountContractType = {
  Mount: "Mount",
} as const;
