/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type MountType = (typeof MountType)[keyof typeof MountType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MountType = {
  Mount: "Mount",
} as const;
