/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type MountAllOf = {
  path: string;
  volumeName: string;
  readOnly: boolean;
  containerName: string;
};
