/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { MountAllOf } from "./mountAllOf";
import type { MountType } from "./mountType";

export type Mount = Contract &
  MountAllOf & {
    Type: MountType;
  };
