/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type MysqlAllOf = {
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  host?: string | null;
  /** @nullable */
  database?: string | null;
  /** @nullable */
  networkName?: string | null;
  admin: boolean;
  installed?: boolean;
  network: string;
};
