/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { MysqlAllOf } from "./mysqlAllOf";
import type { MysqlType } from "./mysqlType";

export type Mysql = Contract &
  MysqlAllOf & {
    Type: MysqlType;
  } & Required<
    Pick<
      Contract &
        MysqlAllOf & {
          Type: MysqlType;
        },
      "Type" | "networkName" | "networkName"
    >
  >;
