/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Resource } from "./resource";
import type { MysqlDatabaseAllOf } from "./mysqlDatabaseAllOf";
import type { MysqlDatabaseType } from "./mysqlDatabaseType";

export type MysqlDatabase = Resource &
  MysqlDatabaseAllOf & {
    Type: MysqlDatabaseType;
  } & Required<
    Pick<
      Resource &
        MysqlDatabaseAllOf & {
          Type: MysqlDatabaseType;
        },
      "Type" | "database" | "host" | "password" | "user"
    >
  >;
