/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type MysqlDatabaseType =
  (typeof MysqlDatabaseType)[keyof typeof MysqlDatabaseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MysqlDatabaseType = {
  MysqlDatabase: "MysqlDatabase",
} as const;
