/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type MysqlType = (typeof MysqlType)[keyof typeof MysqlType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MysqlType = {
  Mysql: "Mysql",
} as const;
