/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type NetworkContractType =
  (typeof NetworkContractType)[keyof typeof NetworkContractType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NetworkContractType = {
  Network: "Network",
} as const;
