/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export interface NetworkContract {
  name: string;
  /** @nullable */
  readonly providerType?: string | null;
  readonly type: string;
}
