/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type NetworkType = (typeof NetworkType)[keyof typeof NetworkType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NetworkType = {
  Network: "Network",
} as const;
