/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Resource } from "./resource";
import type { NetworkAllOf } from "./networkAllOf";
import type { NetworkType } from "./networkType";

export type Network = Resource &
  NetworkAllOf & {
    Type: NetworkType;
  };
