/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { NetworkAllOf } from "./networkAllOf";
import type { NetworkType } from "./networkType";

export type Network = Contract &
  NetworkAllOf & {
    Type: NetworkType;
  } & Required<
    Pick<
      Contract &
        NetworkAllOf & {
          Type: NetworkType;
        },
      "Type"
    >
  >;
