/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { OptionalAllOfContracts } from "./optionalAllOfContracts";

export type OptionalAllOf = {
  /** @nullable */
  value?: boolean | null;
  readonly installed?: boolean;
  contracts: OptionalAllOfContracts;
};
