/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type OptionalType = (typeof OptionalType)[keyof typeof OptionalType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OptionalType = {
  Optional: "Optional",
} as const;
