/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { OptionalAllOfContractsItem } from "./optionalAllOfContractsItem";

export type OptionalAllOf = {
  /** @nullable */
  value?: boolean | null;
  installed?: boolean;
  contracts: OptionalAllOfContractsItem[];
};
