/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { OptionalAllOf } from "./optionalAllOf";
import type { OptionalType } from "./optionalType";

export type Optional = Contract &
  OptionalAllOf & {
    type: OptionalType;
  };
