/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { OverridesContracts } from "./overridesContracts";

export interface Overrides {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  contracts?: OverridesContracts;
}
