/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { PackageAllOfContractsItem } from "./packageAllOfContractsItem";

export type PackageAllOf = {
  contracts: PackageAllOfContractsItem[];
  /** @nullable */
  prefix?: string | null;
  /** @nullable */
  url?: string | null;
};
