/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Application } from "./application";
import type { PackageAllOfContractsItem } from "./packageAllOfContractsItem";

export type PackageAllOf = {
  /** @nullable */
  url?: string | null;
  /** @nullable */
  prefix?: string | null;
  /** @nullable */
  iconUrl?: string | null;
  /** @nullable */
  applicationUrl?: string | null;
  /** @nullable */
  applicationDescription?: string | null;
  /** @nullable */
  shortDescription?: string | null;
  /** @nullable */
  fullDescription?: string | null;
  result?: Application;
  tags: string[];
  contracts: PackageAllOfContractsItem[];
};
