/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type PackageType = (typeof PackageType)[keyof typeof PackageType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackageType = {
  Package: "Package",
} as const;
