/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { ContainerContract } from "./containerContract";
import type { FileContract } from "./fileContract";
import type { HttpEndpointContract } from "./httpEndpointContract";
import type { MountContract } from "./mountContract";
import type { NetworkContract } from "./networkContract";
import type { Package } from "./package";
import type { VolumeContract } from "./volumeContract";
import type { Contract } from "./contract";

export type PackageContractsItem =
  | ContainerContract
  | FileContract
  | HttpEndpointContract
  | MountContract
  | NetworkContract
  | Package
  | VolumeContract
  | Contract;
