/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type ParameterAllOf = {
  /** @nullable */
  value?: string | null;
  /** @nullable */
  defaultValue?: string | null;
};
