/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { ParameterAllOf } from "./parameterAllOf";
import type { ParameterType } from "./parameterType";

export type Parameter = Contract &
  ParameterAllOf & {
    Type: ParameterType;
  } & Required<
    Pick<
      Contract &
        ParameterAllOf & {
          Type: ParameterType;
        },
      "Type"
    >
  >;
