/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type ParameterType = (typeof ParameterType)[keyof typeof ParameterType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParameterType = {
  Parameter: "Parameter",
} as const;
