/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { ExecutionPlanSelector } from "./executionPlanSelector";
import type { Package } from "./package";

export interface ParametersResponse {
  executionPlan: ExecutionPlanSelector;
  package: Package;
}
