/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Package } from "./package";
import type { StringStringKeyValuePair } from "./stringStringKeyValuePair";

export interface ParametersResponse {
  name: string;
  package: Package;
  parameters: StringStringKeyValuePair[][];
}
