/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { ExecutionPlanResponse } from "./executionPlanResponse";
import type { Package } from "./package";

export interface ParametersResponse {
  executionPlan: ExecutionPlanResponse;
  package: Package;
}
