/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type PasswordType = (typeof PasswordType)[keyof typeof PasswordType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PasswordType = {
  Password: "Password",
} as const;
