/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { PasswordAllOf } from "./passwordAllOf";
import type { PasswordType } from "./passwordType";

export type Password = Contract &
  PasswordAllOf & {
    Type: PasswordType;
  } & Required<
    Pick<
      Contract &
        PasswordAllOf & {
          Type: PasswordType;
        },
      "Type"
    >
  >;
