/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { PortEndpointAllOf } from "./portEndpointAllOf";
import type { PortEndpointType } from "./portEndpointType";

export type PortEndpoint = Contract &
  PortEndpointAllOf & {
    Type: PortEndpointType;
  } & Required<
    Pick<
      Contract &
        PortEndpointAllOf & {
          Type: PortEndpointType;
        },
      "Type" | "containerName" | "destinationPort" | "port" | "protocol"
    >
  >;
