/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type PortEndpointType =
  (typeof PortEndpointType)[keyof typeof PortEndpointType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PortEndpointType = {
  PortEndpoint: "PortEndpoint",
} as const;
