/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Protocol } from "./protocol";

export type PortEndpointAllOf = {
  protocol: Protocol;
  port: number;
  destinationPort: number;
  containerName: string;
};
