/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { PortType } from "./portType";

export type PortEndpointContractAllOf = {
  containerName: string;
  destinationPort: number;
  port: number;
  portType: PortType;
};
