/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Protocol } from "./protocol";
import type { DockerPortEndpoint } from "./dockerPortEndpoint";

export type PortEndpointAllOf = {
  protocol: Protocol;
  port: number;
  destinationPort: number;
  result?: DockerPortEndpoint;
  containerName: string;
};
