/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type PortType = (typeof PortType)[keyof typeof PortType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PortType = {
  Tcp: "Tcp",
  Udp: "Udp",
} as const;
