/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type PortEndpointContractType =
  (typeof PortEndpointContractType)[keyof typeof PortEndpointContractType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PortEndpointContractType = {
  PortEndpoint: "PortEndpoint",
} as const;
