/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type PostgresqlType =
  (typeof PostgresqlType)[keyof typeof PostgresqlType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostgresqlType = {
  Postgresql: "Postgresql",
} as const;
