/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type PostgresqlDatabaseType =
  (typeof PostgresqlDatabaseType)[keyof typeof PostgresqlDatabaseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostgresqlDatabaseType = {
  PostgresqlDatabase: "PostgresqlDatabase",
} as const;
