/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { PostgresqlDatabase } from "./postgresqlDatabase";

export type PostgresqlAllOf = {
  /** @nullable */
  databaseName?: string | null;
  admin: boolean;
  result?: PostgresqlDatabase;
  networkName: string;
};
