/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type PostgresqlDatabaseAllOf = {
  user: string;
  password: string;
  host: string;
  /** @nullable */
  database?: string | null;
  networkName: string;
};
