/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { PostgresqlAllOf } from "./postgresqlAllOf";
import type { PostgresqlType } from "./postgresqlType";

export type Postgresql = Contract &
  PostgresqlAllOf & {
    Type: PostgresqlType;
  };
