/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Resource } from "./resource";
import type { PostgresqlDatabaseAllOf } from "./postgresqlDatabaseAllOf";
import type { PostgresqlDatabaseType } from "./postgresqlDatabaseType";

export type PostgresqlDatabase = Resource &
  PostgresqlDatabaseAllOf & {
    Type: PostgresqlDatabaseType;
  };
