/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type Protocol = (typeof Protocol)[keyof typeof Protocol];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Protocol = {
  Tcp: "Tcp",
  Udp: "Udp",
} as const;
