/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { RedisDatabase } from "./redisDatabase";

export type RedisAllOf = {
  result?: RedisDatabase;
  networkName: string;
  containerName: string;
};
