/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type RedisAllOf = {
  /** @nullable */
  container?: string | null;
  /** @nullable */
  volume?: string | null;
  /** @nullable */
  host?: string | null;
  installed?: boolean;
  network: string;
};
