/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type RedisType = (typeof RedisType)[keyof typeof RedisType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RedisType = {
  Redis: "Redis",
} as const;
