/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { RedisAllOf } from "./redisAllOf";
import type { RedisType } from "./redisType";

export type Redis = Contract &
  RedisAllOf & {
    Type: RedisType;
  };
