/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type RedisDatabaseType =
  (typeof RedisDatabaseType)[keyof typeof RedisDatabaseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RedisDatabaseType = {
  RedisDatabase: "RedisDatabase",
} as const;
