/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Resource } from "./resource";
import type { RedisDatabaseAllOf } from "./redisDatabaseAllOf";
import type { RedisDatabaseType } from "./redisDatabaseType";

export type RedisDatabase = Resource &
  RedisDatabaseAllOf & {
    type: RedisDatabaseType;
  };
