/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Resource } from "./resource";
import type { ResolvedParameterAllOf } from "./resolvedParameterAllOf";
import type { ResolvedParameterType } from "./resolvedParameterType";

export type ResolvedParameter = Resource &
  ResolvedParameterAllOf & {
    type: ResolvedParameterType;
  };
