/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type ResolvedParameterType =
  (typeof ResolvedParameterType)[keyof typeof ResolvedParameterType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResolvedParameterType = {
  ResolvedParameter: "ResolvedParameter",
} as const;
