/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type ResolvedDomainType =
  (typeof ResolvedDomainType)[keyof typeof ResolvedDomainType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResolvedDomainType = {
  ResolvedDomain: "ResolvedDomain",
} as const;
