/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { SelectorOption } from "./selectorOption";

export type SelectorAllOf = {
  options: SelectorOption[];
  /** @nullable */
  selectedOption?: string | null;
};
