/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type SelectorType = (typeof SelectorType)[keyof typeof SelectorType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SelectorType = {
  Selector: "Selector",
} as const;
