/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { SelectorOptionContractsItem } from "./selectorOptionContractsItem";

export interface SelectorOption {
  name: string;
  contracts: SelectorOptionContractsItem[];
}
