/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { SelectorAllOf } from "./selectorAllOf";
import type { SelectorType } from "./selectorType";

export type Selector = Contract &
  SelectorAllOf & {
    type: SelectorType;
  };
