/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type SshConnectionType =
  (typeof SshConnectionType)[keyof typeof SshConnectionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SshConnectionType = {
  SshConnection: "SshConnection",
} as const;
