/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { SshConnectionAllOf } from "./sshConnectionAllOf";
import type { SshConnectionType } from "./sshConnectionType";

export type SshConnection = Contract &
  SshConnectionAllOf & {
    type: SshConnectionType;
  };
