/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type SshConnectionAllOf = {
  /** @nullable */
  host?: string | null;
  port: number;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
};
