/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { HandlerExceptionResult } from "./handlerExceptionResult";

export interface State {
  ready: boolean;
  /** @nullable */
  taskName?: string | null;
  error?: HandlerExceptionResult;
}
