/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type SubstituteType =
  (typeof SubstituteType)[keyof typeof SubstituteType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubstituteType = {
  Substitute: "Substitute",
} as const;
