/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export interface TraefikHttpEndpoint {
  dependsOnIds: string[];
  domain: string;
  id: string;
  port: number;
  url: string;
}
