/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type TraefikHttpEndpointType =
  (typeof TraefikHttpEndpointType)[keyof typeof TraefikHttpEndpointType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TraefikHttpEndpointType = {
  TraefikHttpEndpoint: "TraefikHttpEndpoint",
} as const;
