/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Resource } from "./resource";
import type { TraefikHttpEndpointAllOf } from "./traefikHttpEndpointAllOf";
import type { TraefikHttpEndpointType } from "./traefikHttpEndpointType";

export type TraefikHttpEndpoint = Resource &
  TraefikHttpEndpointAllOf & {
    Type: TraefikHttpEndpointType;
  };
