/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type VolumeType = (typeof VolumeType)[keyof typeof VolumeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VolumeType = {
  Volume: "Volume",
} as const;
