/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { VolumeContractAllOf } from "./volumeContractAllOf";
import type { VolumeContractType } from "./volumeContractType";

export type VolumeContract = Contract &
  VolumeContractAllOf & {
    Type: VolumeContractType;
  };
