/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { Contract } from "./contract";
import type { VolumeAllOf } from "./volumeAllOf";
import type { VolumeType } from "./volumeType";

export type Volume = Contract &
  VolumeAllOf & {
    type: VolumeType;
  };
