/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type VolumeAllOf = {
  /** @nullable */
  volumeName?: string | null;
  /** @nullable */
  localPath?: string | null;
};
