/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import type { DockerPortEndpoint } from "./dockerPortEndpoint";
import type { DockerVolume } from "./dockerVolume";
import type { GenericHttpEndpoint } from "./genericHttpEndpoint";
import type { LocalPath } from "./localPath";
import type { TraefikHttpEndpoint } from "./traefikHttpEndpoint";

/**
 * @nullable
 */
export type VolumeAllOfResult =
  | DockerPortEndpoint
  | DockerVolume
  | GenericHttpEndpoint
  | LocalPath
  | TraefikHttpEndpoint
  | null;
