/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */

export type VolumeContractType =
  (typeof VolumeContractType)[keyof typeof VolumeContractType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VolumeContractType = {
  Volume: "Volume",
} as const;
