/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { Application } from "../schemas";
import { customFetch } from "../../custom-fetch";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export type getApplicationsResponse = {
  data: Application[];
  status: number;
};

export const getGetApplicationsUrl = () => {
  return `/api/v1/applications`;
};

export const getApplications = async (
  options?: RequestInit,
): Promise<getApplicationsResponse> => {
  return customFetch<Promise<getApplicationsResponse>>(
    getGetApplicationsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApplicationsQueryKey = () => {
  return [`/api/v1/applications`] as const;
};

export const getGetApplicationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApplications>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApplicationsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplications>>> = ({
    signal,
  }) => getApplications({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApplications>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApplicationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApplications>>
>;
export type GetApplicationsQueryError = unknown;

export function useGetApplications<
  TData = Awaited<ReturnType<typeof getApplications>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getApplications>>,
        TError,
        TData
      >,
      "initialData"
    >;
  request?: SecondParameter<typeof customFetch>;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetApplications<
  TData = Awaited<ReturnType<typeof getApplications>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getApplications>>,
        TError,
        TData
      >,
      "initialData"
    >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetApplications<
  TData = Awaited<ReturnType<typeof getApplications>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useGetApplications<
  TData = Awaited<ReturnType<typeof getApplications>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApplicationsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type deleteApplicationsIdResponse = {
  data: void;
  status: number;
};

export const getDeleteApplicationsIdUrl = (id: string) => {
  return `/api/v1/applications/${id}`;
};

export const deleteApplicationsId = async (
  id: string,
  options?: RequestInit,
): Promise<deleteApplicationsIdResponse> => {
  return customFetch<Promise<deleteApplicationsIdResponse>>(
    getDeleteApplicationsIdUrl(id),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getDeleteApplicationsIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApplicationsId>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApplicationsId>>,
  TError,
  { id: string },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApplicationsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApplicationsId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApplicationsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApplicationsId>>
>;

export type DeleteApplicationsIdMutationError = void;

export const useDeleteApplicationsId = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApplicationsId>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteApplicationsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteApplicationsIdMutationOptions(options);

  return useMutation(mutationOptions);
};
