/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { GetContracts200Item } from "../schemas";

import { customFetch } from "../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getContractsResponse200 = {
  data: GetContracts200Item[];
  status: 200;
};

export type getContractsResponseComposite = getContractsResponse200;

export type getContractsResponse = getContractsResponseComposite & {
  headers: Headers;
};

export const getGetContractsUrl = () => {
  return `/api/v1/contracts`;
};

export const getContracts = async (
  options?: RequestInit,
): Promise<getContractsResponse> => {
  return customFetch<getContractsResponse>(getGetContractsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetContractsQueryKey = () => {
  return [`/api/v1/contracts`] as const;
};

export const getGetContractsQueryOptions = <
  TData = Awaited<ReturnType<typeof getContracts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getContracts>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetContractsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getContracts>>> = ({
    signal,
  }) => getContracts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getContracts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetContractsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getContracts>>
>;
export type GetContractsQueryError = unknown;

export function useGetContracts<
  TData = Awaited<ReturnType<typeof getContracts>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getContracts>>, TError, TData>
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getContracts>>,
        TError,
        Awaited<ReturnType<typeof getContracts>>
      >,
      "initialData"
    >;
  request?: SecondParameter<typeof customFetch>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContracts<
  TData = Awaited<ReturnType<typeof getContracts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getContracts>>, TError, TData>
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getContracts>>,
        TError,
        Awaited<ReturnType<typeof getContracts>>
      >,
      "initialData"
    >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContracts<
  TData = Awaited<ReturnType<typeof getContracts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getContracts>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetContracts<
  TData = Awaited<ReturnType<typeof getContracts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getContracts>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetContractsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type postContractsDiscoverResponse200 = {
  data: void;
  status: 200;
};

export type postContractsDiscoverResponseComposite =
  postContractsDiscoverResponse200;

export type postContractsDiscoverResponse =
  postContractsDiscoverResponseComposite & {
    headers: Headers;
  };

export const getPostContractsDiscoverUrl = () => {
  return `/api/v1/contracts/discover`;
};

export const postContractsDiscover = async (
  options?: RequestInit,
): Promise<postContractsDiscoverResponse> => {
  return customFetch<postContractsDiscoverResponse>(
    getPostContractsDiscoverUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getPostContractsDiscoverMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postContractsDiscover>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postContractsDiscover>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postContractsDiscover"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postContractsDiscover>>,
    void
  > = () => {
    return postContractsDiscover(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostContractsDiscoverMutationResult = NonNullable<
  Awaited<ReturnType<typeof postContractsDiscover>>
>;

export type PostContractsDiscoverMutationError = unknown;

export const usePostContractsDiscover = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postContractsDiscover>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postContractsDiscover>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPostContractsDiscoverMutationOptions(options);

  return useMutation(mutationOptions);
};
