/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { GetContracts200Item } from "../schemas";

import { customFetch } from "../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getContractsResponse200 = {
  data: GetContracts200Item[];
  status: 200;
};

export type getContractsResponseComposite = getContractsResponse200;

export type getContractsResponse = getContractsResponseComposite & {
  headers: Headers;
};

export const getGetContractsUrl = () => {
  return `/api/v1/contracts`;
};

export const getContracts = async (
  options?: RequestInit,
): Promise<getContractsResponse> => {
  return customFetch<getContractsResponse>(getGetContractsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetContractsQueryKey = () => {
  return [`/api/v1/contracts`] as const;
};

export const getGetContractsQueryOptions = <
  TData = Awaited<ReturnType<typeof getContracts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getContracts>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetContractsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getContracts>>> = ({
    signal,
  }) => getContracts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getContracts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetContractsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getContracts>>
>;
export type GetContractsQueryError = unknown;

export function useGetContracts<
  TData = Awaited<ReturnType<typeof getContracts>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getContracts>>, TError, TData>
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getContracts>>,
        TError,
        Awaited<ReturnType<typeof getContracts>>
      >,
      "initialData"
    >;
  request?: SecondParameter<typeof customFetch>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContracts<
  TData = Awaited<ReturnType<typeof getContracts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getContracts>>, TError, TData>
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getContracts>>,
        TError,
        Awaited<ReturnType<typeof getContracts>>
      >,
      "initialData"
    >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContracts<
  TData = Awaited<ReturnType<typeof getContracts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getContracts>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetContracts<
  TData = Awaited<ReturnType<typeof getContracts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getContracts>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetContractsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
