/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Frierun.Server
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { InstallRequest, Package, ParametersResponse } from "../schemas";

export type getPackagesResponse = {
  data: Package[];
  status: number;
};

export const getGetPackagesUrl = () => {
  return `/api/v1/packages`;
};

export const getPackages = async (
  options?: RequestInit,
): Promise<getPackagesResponse> => {
  const res = await fetch(getGetPackagesUrl(), {
    ...options,
    method: "GET",
  });
  const data = await res.json();

  return { status: res.status, data };
};

export const getGetPackagesQueryKey = () => {
  return [`/api/v1/packages`] as const;
};

export const getGetPackagesQueryOptions = <
  TData = Awaited<ReturnType<typeof getPackages>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getPackages>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPackagesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPackages>>> = ({
    signal,
  }) => getPackages({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPackages>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPackagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPackages>>
>;
export type GetPackagesQueryError = unknown;

export function useGetPackages<
  TData = Awaited<ReturnType<typeof getPackages>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getPackages>>, TError, TData>
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getPackages>>,
        TError,
        TData
      >,
      "initialData"
    >;
  fetch?: RequestInit;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetPackages<
  TData = Awaited<ReturnType<typeof getPackages>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getPackages>>, TError, TData>
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getPackages>>,
        TError,
        TData
      >,
      "initialData"
    >;
  fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetPackages<
  TData = Awaited<ReturnType<typeof getPackages>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getPackages>>, TError, TData>
  >;
  fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useGetPackages<
  TData = Awaited<ReturnType<typeof getPackages>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getPackages>>, TError, TData>
  >;
  fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPackagesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type getPackagesIdParametersResponse = {
  data: ParametersResponse;
  status: number;
};

export const getGetPackagesIdParametersUrl = (id: string) => {
  return `/api/v1/packages/${id}/parameters`;
};

export const getPackagesIdParameters = async (
  id: string,
  options?: RequestInit,
): Promise<getPackagesIdParametersResponse> => {
  const res = await fetch(getGetPackagesIdParametersUrl(id), {
    ...options,
    method: "GET",
  });
  const data = await res.json();

  return { status: res.status, data };
};

export const getGetPackagesIdParametersQueryKey = (id: string) => {
  return [`/api/v1/packages/${id}/parameters`] as const;
};

export const getGetPackagesIdParametersQueryOptions = <
  TData = Awaited<ReturnType<typeof getPackagesIdParameters>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPackagesIdParameters>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPackagesIdParametersQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPackagesIdParameters>>
  > = ({ signal }) => getPackagesIdParameters(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPackagesIdParameters>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPackagesIdParametersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPackagesIdParameters>>
>;
export type GetPackagesIdParametersQueryError = unknown;

export function useGetPackagesIdParameters<
  TData = Awaited<ReturnType<typeof getPackagesIdParameters>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPackagesIdParameters>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPackagesIdParameters>>,
          TError,
          TData
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetPackagesIdParameters<
  TData = Awaited<ReturnType<typeof getPackagesIdParameters>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPackagesIdParameters>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPackagesIdParameters>>,
          TError,
          TData
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetPackagesIdParameters<
  TData = Awaited<ReturnType<typeof getPackagesIdParameters>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPackagesIdParameters>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useGetPackagesIdParameters<
  TData = Awaited<ReturnType<typeof getPackagesIdParameters>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPackagesIdParameters>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPackagesIdParametersQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type postPackagesIdResponse = {
  data: void;
  status: number;
};

export const getPostPackagesIdUrl = (id: string) => {
  return `/api/v1/packages/${id}`;
};

export const postPackagesId = async (
  id: string,
  installRequest: InstallRequest,
  options?: RequestInit,
): Promise<postPackagesIdResponse> => {
  const res = await fetch(getPostPackagesIdUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(installRequest),
  });
  const data = await res.json();

  return { status: res.status, data };
};

export const getPostPackagesIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPackagesId>>,
    TError,
    { id: string; data: InstallRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPackagesId>>,
  TError,
  { id: string; data: InstallRequest },
  TContext
> => {
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPackagesId>>,
    { id: string; data: InstallRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postPackagesId(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPackagesIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPackagesId>>
>;
export type PostPackagesIdMutationBody = InstallRequest;
export type PostPackagesIdMutationError = unknown;

export const usePostPackagesId = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPackagesId>>,
    TError,
    { id: string; data: InstallRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationResult<
  Awaited<ReturnType<typeof postPackagesId>>,
  TError,
  { id: string; data: InstallRequest },
  TContext
> => {
  const mutationOptions = getPostPackagesIdMutationOptions(options);

  return useMutation(mutationOptions);
};
