name: Integration tests
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
          
      - name: Install dependencies
        run: dotnet restore --locked-mode
        
      - name: Create node_modules
        run: |
          mkdir -p Client/node_modules
          
      - name: Build
        run: dotnet build
        
      - name: Test with the dotnet CLI
        run: dotnet test Tests.Integration --logger "console;verbosity=normal" -- xUnit.StopOnFail=true
        
      - name: Collect logs
        if: ${{ failure() }}
        run: |
          set -x
          mkdir -p failure-logs
          docker ps -a >>failure-logs/docker-ps
          docker inspect $(docker ps -q) >>failure-logs/docker-inspect
          docker logs $(docker ps -q) >>failure-logs/docker-logs
          journalctl >>failure-logs/journalctl

      - name: Save logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: failure-logs
          path: failure-logs
        
        