name: "traefik"
url: "https://doc.traefik.io/traefik/getting-started/install-traefik/"
shortDescription: "Application proxy"
fullDescription: "Traefik is an open-source Application Proxy that makes publishing your services a fun and easy experience.
  It receives requests on behalf of your system and identifies which components are responsible for handling them,
  and routes them securely."
tags: [ "network", "provider" ]
contracts:
  - type: "Container"
    imageName: "traefik:v3.1"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.httpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.tlschallenge.acme.tlschallenge=true"
    mountDockerSocket: true
    
  - type: "PortEndpoint"
    name: "Web"
    port: 80
    protocol: "tcp"
    
  - type: "PortEndpoint"
    name: "WebSecure"
    port: 443
    protocol: "tcp"