Name: "traefik"
Url: "https://doc.traefik.io/traefik/getting-started/install-traefik/"
ShortDescription: "Application proxy"
FullDescription: "Traefik is an open-source Application Proxy that makes publishing your services a fun and easy experience.
  It receives requests on behalf of your system and identifies which components are responsible for handling them,
  and routes them securely."
Tags: [ "network", "provider" ]
Contracts:
  - Type: "Container"
    ImageName: "traefik:v3.1"
    Command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.httpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.tlschallenge.acme.tlschallenge=true"
    RequireDocker: true
    
  - Type: "PortEndpoint"
    Name: "Web"
    Port: 80
    Protocol: "tcp"
    
  - Type: "PortEndpoint"
    Name: "WebSecure"
    Port: 443
    Protocol: "tcp"